version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sisu_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: